language: node_js
node_js:
    - '8.10'
    - 'lts/*'
    - 'node'

install:
    - make install-sedy

script: make test

cache:
    directories: sedy/node_modules

branches:
    only:
        - master
