language: node_js
node_js:
    - "6.10" # version used by AWS Lambda
    - "6"
    - "8"

install:
    - make install-sedy

script: make test

cache:
    directories:
        sedy/node_modules

branches:
  only:
    - master
